# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'constituencies',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr_line_1', models.CharField(max_length=100)),
                ('addr_line_2', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('addr_line_1', models.CharField(max_length=100)),
                ('addr_line_2', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=14)),
                ('used_vote', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.Station')),
            ],
        ),
    ]
