# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='addr_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
