# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20170601_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
        migrations.AddField(
            model_name='voter',
            name='active_pin',
            field=models.BooleanField(default=False),
        ),
    ]
